version: "3.9"  # optional since v1.27.0
services:
  web:
    build: 
      context: ../sampleDocker
      dockerfile: Dockerfile
    ports:
      - "8100:80"
    volumes:
      - .:/code
      - logvolume01:/var/log
    links:
      - redis
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    networks:
      - webnet
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "/Users/bill/dockermounts:/data"
    networks:
      - webnet
volumes:
  logvolume01: {}
networks:
  webnet: